In [1]:
import numpy as np

# Exercise 1: Array Creation and Manipulation
print("Exercise 1:")
arr1 = np.arange(0, 10)
print(arr1)
print()

# Exercise 2: Type Conversion and Array Operations
print("Exercise 2:")
arr2 = np.array([3.14, 2.17, 0, 1, 2]).astype(int)
print(arr2)
print()

# Exercise 3: Working with Multi-Dimensional Arrays
print("Exercise 3:")
arr3 = np.arange(1, 10).reshape(3, 3)
print(arr3)
print()

# Exercise 4: Creating Multi-Dimensional Array with Random Numbers
print("Exercise 4:")
arr4 = np.random.rand(4, 5)
print(arr4)
print()

# Exercise 5: Indexing Arrays
print("Exercise 5:")
arr5 = np.array([[21, 22, 23, 22, 22], [20, 21, 22, 23, 24], [21, 22, 23, 22, 22]])
second_row = arr5[1]
print(second_row)
print()

# Exercise 6: Reversing elements
print("Exercise 6:")
arr6 = np.arange(0, 10)
arr6_reversed = arr6[::-1]
print(arr6_reversed)
print()

# Exercise 7: Identity Matrix
print("Exercise 7:")
arr7 = np.eye(4)
print(arr7)
print()

# Exercise 8: Simple Aggregate Funcs
print("Exercise 8:")
arr8 = np.arange(0, 10)
sum_val = np.sum(arr8)
avg_val = np.average(arr8)
print(f"Sum: {sum_val}, Average: {avg_val}")
print()

# Exercise 9: Create Array and Change its Structure
print("Exercise 9:")
arr9 = np.arange(1, 21).reshape(4, 5)
print(arr9)
print()

# Exercise 10: Conditional Selection of Values
print("Exercise 10:")
arr10 = np.arange(0, 10)
odd_numbers = arr10[arr10 % 2 != 0]
print(odd_numbers)

Exercise 1:
[0 1 2 3 4 5 6 7 8 9]

Exercise 2:
[3 2 0 1 2]

Exercise 3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exercise 4:
[[0.97441508 0.58710198 0.06572445 0.00494317 0.23824951]
 [0.30830852 0.90057573 0.83513738 0.68197926 0.44707666]
 [0.10232729 0.61397575 0.18044241 0.90879208 0.44839575]
 [0.26976257 0.86340576 0.95116058 0.45333624 0.15303767]]

Exercise 5:
[20 21 22 23 24]

Exercise 6:
[9 8 7 6 5 4 3 2 1 0]

Exercise 7:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Exercise 8:
Sum: 45, Average: 4.5

Exercise 9:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Exercise 10:
[1 3 5 7 9]
